### PR TITLE
new historic imagery index download map component

### PR DESCRIPTION
**Pull request by adambreznicky**
new download map component for historical aerial template type datasets. replaces coverage map on desktop/large screens if the collection has an ls4 index service url

### CODE REVIEW

**Comment by adambreznicky** [comment]
Selection_058

in historical index download maps, on layer change throws an error related to the hover layer. landing on the map on load works fine, but changing layers either way always throws a layer error

**Comment by JasonKleinert** [comment]
I'll check into it

**Comment by adambreznicky** [comment]
Selection_059

the regular download map seems to be working fine for most collections, but collections with multiple layers (NAIP) throws errors. specifically, on load it seems to load both layers automatically (opposed to just the one initially) and switching layers blasts layer errors in the console

**Comment by JasonKleinert** [comment]
Ok. I resolved the historical map error in commit b50c36a35ecd9d8b17d4028918f66da371b762b1. I'll check out this one now.

**Comment by JasonKleinert** [comment]
I think I got it all worked out now. Resolved in commit e230045eb75cf9b570767f233eb5d7d4d29815e6.

**Pull request merged**
