### PR TITLE
Package updates

### PR DESCRIPTION
**Pull request by JasonKleinert**
I updated all package versions to latest except @material packages, they were brought up to the second latest version till a webpack/node-sass issue is cleared up.

### CODE REVIEW

**Comment by adambreznicky** [comment]
looks good for the most part. was able to pull the code, install the new packages, and build no problem. browsing around the app everything seems to be working as expected with the 2 CSS exceptions:
1) mobile easy buttons (zoom and full extent) css is not centered. this issue also applies to the historical imagery coverage map (both desktop and mobile)
Selection_013

2) search bar X css is riding high on both desktop and mobile
Selection_014


wondering, did you update NODE also? or should/is that a separate issue?
also, @material has already been bumped up to v5 from 4. 

thanks for tackling this @JasonKleinert !

**Comment by JasonKleinert** [comment]
Thanks for building and testing. I forgot to update the sass for those buttons on mobile, I had to for desktop. I didn't move to @material 5.0.0 because of an issue with node-sass. It looks like it should be updated at some point to play nice with the new material stuff, so I figured we should hold off for now. I'll fix the sass stuff and see where we're at.

**Comment by JasonKleinert** [comment]
I updated the sass for those map controls and the search bar @adambreznicky

**Comment by adambreznicky** [comment]
looks good!

**Pull request merged**
