### PR TITLE
carousel and other package updates

### PR DESCRIPTION
**Pull request by adambreznicky**
addresses #257 carousel package issue (half resolves the deprecated lifecycle issue). 
carousel package updated along with all other outdated packages (excluding @material). removed map nav control clause which was causing an inconsistent bug where the nav control didn't always work

### CODE REVIEW

**Comment by adambreznicky** [comment]
i pork rolled into this PR geofilter responsive disabling based on window size change events. although personally tested, please re-test the geofilter map component during review to ensure it consistently maintains the expected behavior.
muchas gracias

**Comment by adambreznicky** [comment]
i pork rolled into this PR new preview layer for collection download maps with wms_link and a couple package updates that had deprecated code

**Comment by adambreznicky** [comment]
pork rolled added enhancement to include historical collections with index wms services into 'WMS Service' sidebar filter

**Comment by jwhaney** [comment]
so it appears like this bug exists on the production site now so not related to the work you did here, but the geofilter map draw tools, specifically the delete tool isn't working. draw a box and try to use the delete button to remove it and it doesn't seem to work.

we probably just need to create a new bug issue for that but just documenting it here because i discovered it in my review here.

**Comment by jwhaney** [comment]
seems like the fullscreen control is buggy in the download maps. it's not getting all the way to the fullscreen. it tries then falls back to regular screen. i was reviewing this collection when i discovered the issue: Dewitt County Lidar, id:9d0966f6-2a89-4734-a406-2fd112831a3e

**Pull request merged**
